### ISSUE TITLE
[P/L Addon] Transfer and deposit value issue

### ISSUE THREAD

**Issue by strongwinderic** [mani-coder/wealthica-addons#4]
Hey! I think I caught an issue.

I have a transfer out from account A to account B.
The plugin calculates deposits value well on account B:

![image](https://user-images.githubusercontent.com/9271579/124331219-8d57a800-db54-11eb-8bf9-402bfcaf92a5.png)

But when I check on account A, I am expecting it to decrease the deposits on that date:

![image](https://user-images.githubusercontent.com/9271579/124330887-f7bc1880-db53-11eb-8ef1-c12b607541a3.png)

Check how the portfolio value line decreases, but the deposits line doesn't.

**Comment by mani-coder** [comment]
Hi,

What is your brokerage account? Transfers work pretty well with Questrade.

 
Also, can you check the transfer transactions and see if there are two transactions recorded?

**Comment by strongwinderic** [comment]
Thank you for the feedback!

My brokerage is Wealthsimple.
Yes, I checked and I have 2 transfer transactions, one with a positive value for one account and another one with the respective negative value for the other account:

![image](https://user-images.githubusercontent.com/9271579/124488972-17328b80-dd76-11eb-836d-b58ffc068b61.png)

Is it correct both marked as TRANSFER, or one of them should be another transaction type?

**Comment by mani-coder** [comment]
Yeah, tat looks good, let me check the code. I remember doing transfers with Wealthsimple, let me check it out.

**Comment by mani-coder** [comment]
Okay, I have this weird condition for handling `transfer` types in code. I just get rid of it, can you let me know whether it fixed it?

Ideally, I don't want to include security transfers in the deposits/withdrawals. 

```
 if (type === 'transfer') {
        if (
          // FX and journal over shouldn't be treated as deposits.
          !['FXT', 'BRW', 'ExchTrade'].includes(transaction.origin_type) &&
          // Security transfer over..
          !transaction.symbol
        ) {
          portfolioData.deposit += amount;
       }
}
```

**Comment by mani-coder** [comment]
I checked out the change in staging and it was good. I release it to production, the cache would get updated in an hour so.

**Comment by strongwinderic** [comment]
@mani-coder It did not work, but I think I know why. I opened a PR with a proposed fix, detailing the scenario. Let me know if it makes sense.

**Comment by mani-coder** [comment]
https://github.com/mani-coder/wealthica-addons/pull/5 should fix this. Thanks!
