### ISSUE TITLE
Around 2 days ago the calculation for total deposits jumped quite substantially

### ISSUE THREAD

**Issue by bbgobie** [mani-coder/wealthica-addons#6]
![image](https://user-images.githubusercontent.com/2893221/124934861-1fd3cd80-dfd3-11eb-8c1a-c8c0484d6e5d.png)
Previously my deposits was will below portfolio value and is closer to what I would've suspected.  Will have to go through a lot of statements to figure out the correct figure myself, but maybe you know if something was pushed to production around 2 days ago? It might even have started yesterday?

The account in the graph includes transfers from another institution. Unfortunately I wasn't using Wealthica since the beginning of that account so I can't see exactly where it went wrong.

**Comment by bbgobie** [comment]
I've just added up all the deposits and transfers into that account in its history.
Assuming interest, rebates, dividends etc is not included in the calculation, my starting total deposits really should've been about 235,000.

**Comment by mani-coder** [comment]
I guess, it should have happened yesterday. We made a change to include the security transfers as deposits which is supposed to mess up the real cash deposits calculation. 

Let me revert that.

**Comment by mani-coder** [comment]
https://github.com/mani-coder/wealthica-addons/pull/5 -- this the request where we made the change.

**Comment by mani-coder** [comment]
@bbgobie I have pushed out the change to exclude the security transfers from being included in the deposits. That would potentially correct your issue. 

Please let me know if it's not fixed, I have also made one more change where we started including the FX transactions into deposit calculations which shouldn't be an issue because the transfers are within CAD & USD of the same account most likely.

**Comment by bbgobie** [comment]
Thanks, its a lot closer, still showing starting deposit value at about 281 though.
![image](https://user-images.githubusercontent.com/2893221/124967716-ba8fd480-dff2-11eb-9b3a-57c0f455d37e.png)

I think the FX might be it, although I guess it depends on how you calculate.
In QT, US/CA is 1 account, but in wealthica, they show as different accounts,
eg Questrade TFSA USD
Questrade TFSA CAD

Although as you say, they should even out.  It could be my fault? I usually use Norbert Gambit to convert, I'm not sure if those transactions are being reflected properly.

To be honest there's a few other questionable transactions that I'm not sure Wealthica knows how to deal with and I'm not sure if I have them fixed up correctly, like Spacs, warrants.  But the sum of those shouldn't put me that far off.

PS. thanks for the crazy quick response!

**Comment by mani-coder** [comment]
Okies, thanks for the response, I will exclude the FX transfers from the deposits. It usually takes around an hour for the P/L timeline addon to reflect the changes.

If you want to check out the changes quickly, you can use the Wealthica developer add-on and test the changes quickly.

Use this URL: https://wealthica-dr.mani-coder.dev/mani-coder/wealthica-portfolio-addon/?developer

![image](https://user-images.githubusercontent.com/11651746/124971471-11d77a00-dfde-11eb-890a-0ad43da9dd2b.png)

Click on settings --> configure in the developer add-on and add above URL.
![image](https://user-images.githubusercontent.com/11651746/124971534-2a479480-dfde-11eb-85d1-06f7524e28a8.png)

**Comment by bbgobie** [comment]
Thanks so much for looking at this so quickly! Great add on by the way
