### ISSUE TITLE
[P/L Addon]

### ISSUE THREAD

**Issue by TheFinancialPathfinder** [mani-coder/wealthica-addons#8]
Hello, I'm not sure why, but in the News tab, it only shows 2 of my holdings.
http://prntscr.com/1adpqw5

In the holdings tab, it shows all of them though.
http://prntscr.com/1adqp8c

So it was a little disappointing to not see all of them there, as I was looking forward to have the ability to filter news by each stock. Hope you're able to fix that!

Anyway, I am enjoying your app, thanks for it!

**Comment by mani-coder** [comment]
Thank you, I am checking it. @TheFinancialPathfinder

**Comment by mani-coder** [comment]
this is fixed now.

**Comment by TheFinancialPathfinder** [comment]
Thank you! I did want to point out, I'm not sure if it's because of the information being pulled to the app isn't quite correct, or if what you have isn't quite correct, but...
GDNP is on the TSX Venture or TSX-V
NEXE is also on the TSX-V
PSYK is on the Aequitas Neo Exchange

So I don't think those are .TO stocks. I think the TSX-V stocks are .V, and the Aequitas Neo Exchange stocks are .NE, at least according to yahoo finance.

Thank you!
